### ISSUE TITLE
Panel Packs pt II

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1161]
List of things to do:
- [ ] Candidates list. Enable Filters so we can see candidates yet to be assigned to a panel

- [ ] Panel packs for scenario test marking

- [ ] Require teams to upload a candidate assessment/report template at the exercise creation stage and then generate a report template for each candidate at the sift panel pack stage, to be exported to for each candidate

_[ ] update search function in panel pack

 [ ] One or two exercises that requires  the  Selection  Exercise Team add  additional questions at the end of Self assessment

[ ]Ability to export the folders as follows: Panel>Panel Member>Candidates. At the moment, it exports  the folders as Panel>Candidates
