### ISSUE TITLE
Automated JO handover

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1167]
**NB. This ticket is still being developed and is in DRAFT**

## Overview
An automated transfer of data to the Judicial Office’s (JO) eHR platform needs to be completed for candidates in the ‘‘Handover’ stage who have been ‘Approved for immediate appointment’. 

In the event of a s94 (call off list), the data from candidates in the ‘Recommended’ stage who have been ‘Approved for future appointment’ may also need to be automatically transferred on request. 

**User roles / access**
An authenticated JAC staff user with the correct access level (role) will need the ability to navigate the Admin app and select to ‘transfer handover data’ to Judicial Office, which will transfer the handover data of the selected candidate/s.  

**Architecture**
An overview of the intended solution can be found in our [documentation](https://jac-uk.github.io/documentation/features/handover/)

**Handover data**
![Screenshot 2021-02-26 at 12.35.08.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/4c2a8f49-d21a-4be4-9139-6fdd936bf490)

**External API**
We will be connecting to the eHR ATS API from a company called CIPHR
API details will be made available when the work has been approved

---

## Approach / key tasks

**Documentation**
- [x] Overview notes, references & links
- [x] Architecture diagram
- [ ] Identify any data model changes

**Pre-requisites**
- [x] apply#616 Add first & last name (and title?)
- [x] apply#615 Add title to application form
- [ ] ~~Admin & Apply. Make use of first & last name field, instead of fullName.~~ OUTSIDE THE SCOPE OF THIS EPIC
- [ ] Collect eJudiciary email address. @KateMJAC are we doing this at the end of the process?
- [ ] Obtain API docs (see latest proposal document from Judicial Office)
- [x] Obtain list of fields to be transferred (see latest proposal document from Judicial Office)

**Tasks**
- [x] digital-platform#505 Set up cloud function
- [x] admin#1192 UI to call cloud function & results page
- [ ] digital-platform#607 Platform. Assign static IP (range) to cloud function
- [ ] Platform. Write unit tests and API integration tests
- [ ] digital-platform#1394 Platform. Connect to external API, for testing
- [ ] Manual testing & verification - lots! Need to check input data vs results of import; existing account vs new; data format for addresses, dates etc
- [ ] Platform. Set up production environment

**Testing**
- [ ] Unit tests
- [ ] Integration tests
- [ ] Manual testing with JO
- [ ] Manual testing with JAC

**Comment by warrensearle** [comment]
Hey @KateMJAC looking at the transfer fields reminded me that I _think_ we need to enable/use the "Consent to character checks" form as it is on here that we collect address details. We also collect title. _I am assuming it is not being used yet_

So we should review the following for the best place to ask for first name, last name, title, eJudiciary email etc.
- Initial application form
- Consent to character checks form (if it is going to be used)
- NEW. Pre-handover form

I think we decided first name, last name would be on the initial application form. Perhaps title should stay on the consent form. Then it's just a case of deciding about eJudiciary address. We could have a new pre-handover form which acts as a catch-all and asks for any missing data at that point in the process.
