### ISSUE TITLE
Equal Merit Zone Tie-break Tests

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1244]
We require the functionality on our digital platform to create and run online tests for candidates, to support the JAC’s [equal merit](https://judicialappointments.gov.uk/equality-and-diversity/diversity-and-equality-measures/equal-merit/) approach. 

The use of the test will follow a decision made by the Selection and Character Committee (SCC) that there is zone of equal merit following the selection day stage, but members of the SCC cannot make a recommendation on the basis of ethnicity or gender.

This online test format will mirror the existing qualifying tests feature on the platform. The main difference being a new workflow needs to be created, allowing admins to select candidates for the EMZ tie-break online test at the selection day stage/end of the exercise process. 

**Admin**

- [ ] Admin users will be required to create the test after candidates have applied for an exercise and participated in selection days. 

- [ ] Admin users will need to allocate applicants to a test after selection days and SCC have taken place. 

- [ ] Admin users will be required to designate a day for and timeframe within which the test will take place. 

- [ ] Admin users will need to supply a scenario onscreen and related questions for candidates participating in the test. 

- [ ] Admin users will need to designate a time limit for the test and have the option to change time limits for candidates that require reasonable adjustments. 

- [ ] After candidates take the test, admin users will be required to download responses for scoring and processing. 

- [ ] Admin users will be required to allocate a result to each participating candidate and process them accordingly. 

**Apply**

- [ ] Once allocated to the test candidates will need to be able to see the ‘title’, ‘status’ and ‘start date’/time of the test in the ‘Online tests’ section of their profile. 

- [ ] The test will need to appear in the either the ‘Open’, ‘Future’ or ‘Past tabs within the ‘Online tests’ display. 

- [ ] On the day of the test candidates will need to be able to select a link to take them to an information/instruction page. 

- [ ] Once they have confirmed they have read and understood the instructions, candidates will start the test. 

- [ ] While completing the test, candidates will need to see a timer counting down at the top of their screen, to alert them of how much time they have left to take the test. When there is only a minute left on the test the candidates will need to be alerted of this. 

- [ ] As candidates will be answering in free text fields, an auto save function will be needed to ensure work is not lost. 

- [ ] Candidates will also need the ability to skip and come back to questions. 

- [ ] When candidates answer all questions, they need the ability to review them before submitting the test. 

- [ ] The candidates need to submit the test and receive confirmation that they have done so, or once the timer has run out the test needs to be auto-submitted and the candidate notified. 

Having the test run on the platform is the best option for admin and end-users. Varies issues were exerienced with recent dry-run and live pilot using Google Forms.

**Comment by HalcyonJAC** [comment]
Questions

- Can 'under-representation' be defined and quantified in a formula?

**Comment by HalcyonJAC** [comment]
Design Ideas:

- Database
  - [x] EMZ tie-breaker tests should have an `isTieBreaker` flag against them to distinguish them from other Qualifying Tests. This will enable them to be reported on seperately if required.
- Admin
  - [x] Since EM Tie-breakers are going to be very simliar to QTs, reuse existing QT code/components where possible
  - [x] The system should not allow an EMZ tie-breaker test to be created for an exercise that has no Qualifying Tests.
  - [x] The system should not allow an EMZ tie-breaker test to be created where the `startDate` or `endDate` of the test is outside of the Equal Marit Second Stage date-range for the exercise.
  - [x] The system should not allow an EMZ tie-breaker test to be opened/started while the Qualifying Tests for the exercise are still open.
  - [ ] When initialising QTs a `qualifyingTestResponse` document is created for each candidate. For tie-breakers these should should have an `isTieBreaker` flag set against them so they can be easily distinguished from the main QT responses.
  - [ ] EMZ Tie-breakers should not appear on existing QT reports (i.e., they will be on a new (seperate) report instead).
- Apply
  - Since EM Tie-breakers are going to be very simliar to QTs, reuse existing QT code/components where possible
  - [ ]

**Comment by KateMJAC** [comment]
Hello @HalcyonJAC I know that we ran through this in our meeting last week, but I have some additional answers for you: 

Do exercises ever have multiple Qualifying Tests? - **Yes, in that an exercise could hold a critical analysis and situational judge QT and then run a scenario QT after those as past of the shortlisting exercie.** 

Will exercises ever need to have multiple EMZ tie-breaker tests? - **at this stage no. It is the one scenio test after selection days and the recommendation SCC meeting.** 

Will there be any other need (now or in the future) for tie-breaker tests, other than for Equal Merit purposes? **Not to out knowledge.**

Will the system ever need to be able to identify instances of "under-representation" itself or will this always be identified outside of the system (i.e. by the SCC)? **This is all determined external to the platform**

    Further to the above, if the system needs to be able to identify "under-representation" itself, how can it be defined / quantified in a formula? **As above**

The requirements above state that the JAC will need to create tie-breaker test sometimes after candidates have applied for an exercise and participated in selection days. Has the option of creating the tie-breaker tests beforehand been considered?, i.e., to eliminate any potential bias in the test or to simply 'get ahead' in the workflow? ****It has been confirmed that: The test will only come into force if the SCC, at the final recommendation stage, cannot determine who to recommend should there be a zone of equal merit.  So it is not shortlisting tool, as all the candidates who use it are selectable. ****

**In short this will only be used after selection days and not earlier in the exercise process.** 

How many candidates per EMZ tie-breaker test are anticipated? **This may vary depending on the exercise, however I can confirm that is will be significantly less than the numbers that participate in QTs. It is more likely to be in low double or single digits.**

Has the possibility of candidates applying for multiple roles been considered? **The test will need to be associated with a particular exercise, so it shouldn't matter if the candidate allocated to a test is applying for other role. The exercises are seperate at that stage of the process.** 

    If candidates could voice their preferences, i.e. 1st choice position, 2nd choice position, 3rd choice position, etc, would this help?
    Do candidates ever turn an offer for a position down (i.e. in favour of another position)? This would potentially free-up a position for a EMZ candidate.
**Candidates do withdraw from exercises. this would have to occur before the test takes place for another candidate to be allocated.** 

Are there any specific reporting requirements for EMZ tie-breaker tests? Do existing QT reports need extending? Do new reports need creating? **Reports can replicate what is currently in place for scenario QTs.** 

Do you want EMZ Tie-breakers to be a new type of QT (and therefore listed with other QTs) or in a new section entirely? i.e. add an EMZ Tie-Breakers link under Tasks? **The EMZ tests need to be their own task listed seperate to QTs.**

**Comment by HalcyonJAC** [comment]
Thanks again for getting answers (above) to my questions Kate. Very helpful :)

Here are my notes from our meeting today:

- [ ] Allow a tie-breaker test to be created even if no QTs have been created for the exercise.
  - Note: Sometimes no QTs are created for an exercise, i.e., selection is done via phone interviews.
- [ ] Tie-breakers will always be scenario tests. So, when creating a tie-breaker test the system should choose the 'Scenario' test type and prevent the user from choosing another test test type.
  - Note: Related to the above - I presume that dry-runs are still required as an option here.
- [ ] When choosing candidates to include in a tie-breaker the Applications dropdown should only consider candidates that have the EMP flag set against them.

**Comment by HalcyonJAC** [comment]
Apply portal
  - [x] Rename _Qualifying tests_ to _Online tests_

**Comment by HalcyonJAC** [comment]
Following a review with Kate...

- [ ] Apply
  - [ ] Rename `qualifying-test` to `online-test` in URLs

**Comment by KateMJAC** [comment]
Ticket not tested by prevous week's testers. 

Sent to UTG on 29/06/21. Awaiting feedback.

**Comment by KateMJAC** [comment]
I positive test confirmed. Sent to w/c 5 July testers for more feedback.

**Comment by KateMJAC** [comment]
Unable to release this work due to merge conflicts. Awaiting action by devs.
