### ISSUE TITLE
Application Enhancements

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1267]
Since the MVP delivery of the application form there have been amendments along the way based on feedback from both admin and apply side users. 

We have received recent feedback from admin users with regards to certain sections or fields in the application form that don’t adequately collect the information required. This causes issues throughout the exercise process and requires admin users to contact candidates requesting further information. 

The highlighted areas on admin and apply side in need of enhancement include: 

- [x] Gaps in employment – This question needs to be removed if the ‘Non legal’ option is selected under the ‘Vacancy information’ section. 
- [ ] A tick box for candidates to confirm that they meet the eligibility criteria for the exercise.
- [x] Additional dates field for candidates who select ‘I did not complete pupillage’ under the Qualifications section. 
- [x] Additional question fields in relation to legal experience. 
- [x] Location preferences – ensuring candidates can’t list the same preference twice and that candidate preference aren’t reordered by the platform. 
- [x] RTF for open text fields on Admin – this is required when Admins select the ‘Does additional selection criteria (ASC) apply?’ option under the ‘Eligibility information’ section. 

We need to consider the GDS Service Manual and Design System when implementing these changes.
