### ISSUE TITLE
QTs part III

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1277]
_Placeholder for QTs part III epic. 
More detail to be added. 
For now let's write task lists and we can convert into issue tickets later.
Existing tickets can be moved into this epic_

**New enhancements & bugfixes**
- [ ] Apply. Test should only be able to be opened on one browser window at a time
- [ ] SPIKE: Consider moving QTs into separate app(s) so that we can have a 'QT code freeze'
- [ ] Admin. Response view. Change 'Questions' tab to 'Answers'
- [ ] Admin. Response view for scenarios. Remove the question and scenario text (or collapse it if it's needed)
