### ISSUE TITLE
Multiple role exercises

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1342]
Enable a single exercise to have multiple roles (appointments). The application process is the same across all roles and includes collecting which role(s) a candidate is interested in applying for.

Applications are processed for each role and a candidate may progress to a different stage for each. For example a candidate may be unsuitable for one role but recommended for another.

### Done when...

 - [x] JAC staff can add roles to an exercise
 - [x] Candidate can indicate which role(s) I am applying for
 - [x] JAC staff can view which role(s) candidate has applied for
 - [ ] JAC staff can specify which role to process applications for
 - [ ] JAC staff can update stages & status for a specific role
 - [ ] JAC staff can view reports for a specific role
 - [ ] JAC staff can download data for a specific role

**Comment by warrensearle** [comment]
I reviewed progress today (4th October 2021) and the following work has been completed by @HalcyonJAC
 - [x] JAC staff can add roles to an exercise
 - [x] Candidate can indicate which role(s) I am applying for
 - [x] JAC staff can view which role(s) candidate has applied for

**Comment by warrensearle** [comment]
This was partially implemented but out of date now so was closed
