### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1396]
**The why ** 📣

To allow policy, diversity and engagement colleagues to analyse each QT exercise by overlaying key data to look at the relationship between progress or diverse groups throughout the process.

The SLT are not superusers of the platform, nor need to be. They need certain information made readily available to them via a Dashboard, of which, the criteria can be found below. 

**User story** 📖

As an SLT member l want to obtain data from the platform in the form of a dashboard so that I can easily digest it but I will also need the option to download the data for off system analysis. 

**Acceptance criteria** ☑️

- [ ] As a user, I want to be directed to the dashboard once I choose an exercise

- [ ] As a user, I need to be able to export data from the dashboard 

- [ ] As a user, I need to be able to refresh the dashboard and be presented with the latest exercise data

- [ ] As a user, I need to be able to add and remove the criteria I need to view on the candidate breakdown chart

**Technical documentation** 👩‍💻

Documentation link can be found here 👉 https://docs.google.com/document/d/1Xpd-_ei94-75N7tYXElf91NmVFHL8-_Y9La4oTihkgA/edit

**Design documentation** 👩‍🎨

UI link can be found here 👉  https://www.figma.com/proto/zJI7oT9EqEWQpgRWJ53lDp/JAC-Dashboard?node-id=133%3A1490&scaling=min-zoom&page-id=13%3A371&starting-point-node-id=133%3A1490&show-proto-sidebar=1

**UAT test documentation** 🙂

Documentation link can be found here 👉 https://docs.google.com/spreadsheets/d/1rxz2JXd3Cg-Z9FFLw2kjsTNu-mBccxGkXqmi5y03jcc/edit#gid=0

**Who should test** 🔍

TBD

**How to test (insert video and testing steps)** 🎥

Insert screen recording here 

**Deployment risk** ⚠️
