### ISSUE TITLE
Eligibility Report - Part 2

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1658]
As a user I need to be able to set recommendations for whether a candidate is eligible or not, and then download an SCC paper template with candidates in the correct sections.

- [ ] Design Mock ups

- [ ] Test and feedback with Teams

- [ ] Build V1 of Feature

https://docs.google.com/document/d/1eLRmGOzmo76KOoNAvmDcyf4rfHfS43OrUgGCiG4S8bs/edit
