### ISSUE TITLE
Welsh Language Applications

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1778]
The Welsh Matters Committee have requested that all exercises which have a welsh post should offer the candidate the opportunity to complete an application in Welsh.

The JAC is therefore looking at how it can create a welsh application form for candidates to apply for vacancies.

Background information and some of the options considered can be found in this [document](https://docs.google.com/document/d/1sVNTCw3cZK-Y87KO9CZci5YxCY_a2yiIDTXDGYLRjn4/edit#).

Note that all translated content will be provided by a translator.

---

**Apply**
- [x] Spike: Consider options and propose an outline plan @warrensearle
- [ ] Design: How can a candidate opt to complete their application in Welsh? jac-uk/apply#963 @HalcyonJAC 
- [x] Design: A pattern for switching between English and Welsh language jac-uk/apply#962 @warrensearle and @HalcyonJAC 
- [x] Build: Enable candidates to apply for a vacancy in Welsh jac-uk/apply#961 @HalcyonJAC 

**Translation**
- [x] Design: A plan for providing translator with content and for consuming the translations back again @warrensearle and @HalcyonJAC  
- [x] Provide translator with text to be translated (in a format that is useful for translator as well as for us to consume) @HalcyonJAC 

**Admin**
 - [ ] Indicate that an application was made using the Welsh language application form jac-uk/admin#1813 @HalcyonJAC
