### ISSUE TITLE
QT Backwards compatibility

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1883]
We have new features to help with processing applications.

This is great for new exercises but here we are considering the impact on existing exercises. Some exercises will have been completed and, perhaps, archived. Other exercises with be 'part-way through' and so will have completed some application processing tasks.

We would like to:
 - gather as much historical data as we can
 - ensure 'part-way through' exercises can make full use of the new functionality

**Tasks**
 - [x] Default to using the new QT Platform
 - [x] Ensure CA, SJ and QT tasks update the status to be compatible with existing statuses (if we are updating status)
 - [x] Tasks should support QTs already carried out on digital platform
 - [x] Status updates should be optional for past tasks
