### ISSUE TITLE
Configure Pre-selection day workflow

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2191]
**Feature(s) Description** 
Using the new workflow pattern/framework add a new task with the following steps:
 - Get started
 - Configure which data is being collected from candidates
 - Monitor candidate responses
 - Completed

**Task list:**
- [x] Set up navigation & pages for Pre-selection day
- [x] Configure which data is being collected from candidates
- [x] Select panellists (OR add panellists OR add panels+panellists)

**Testing Instructions**
TBC

**Comment by warrensearle** [comment]
Following User Testing on 6 Dec:

- [ ] On candidate responses page we need a call-to-action button for the team to "Close form and complete this task" as there is no longer a way to get to the completed screen & mark the task as DONE
