### ISSUE TITLE
Monitor Candidate Data

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2192]
**Feature**
Refer to existing functionality in Character Checks and ensure SETs can request data from candidates and track their responses. Also see Pre-selection day workflow and documentation.

**Task list:**
- [x] View status of candidate data requests (not requested, requested, started, completed)
- [ ] Search candidates
- [ ] Send (notify) requests to all
- [x] Send (notify) requests to custom selection
- [ ] Send (notify) reminders to all candidates who haven't completed
- [x] Send (notify) reminders to custom selection
- [ ] Continue / close the candidate forms

**Miro Board**
https://miro.com/app/board/uXjVNez9BuM=/?moveToWidget=3458764567208308949&cot=14

**Comment by HalcyonJAC** [comment]
@nickaddy I will create the email templates on Notify. Do we have the content of the email templates:
- Request of pre-selection day questionnaire
- Reminder of pre-selection day questionnaire

**Comment by nickaddy** [comment]
@HalcyonJAC Can we unpack what the user is requesting here?
