### ISSUE TITLE
Handling files and virus scanning

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#221]
From Pen Test team:

"The Downloads area within the exercise creation page on the admin website that lets you upload templates does not appear to block the upload of files that contain viruses (EICAR was uploaded and downloaded as a test)."

Firebase storage does not include any virus scanning by default - it does not concern itself with content of files it stores.

Google Drive includes virus scanning on file download.

There may be a virus detection API, from Google or other, we can integrate into a cloud function that's triggered on upload....and similar on download.

**Comment by crablab** [comment]
The Notify API carries out some virus scanning on the submitted PDFs. I will ask on XGov Slack about how they are doing this, in case there are some learnings we could use :)

**Comment by crablab** [comment]
Notify use ClamAV (implemented here: https://github.com/alphagov/notifications-antivirus). 

Their specific codebase is using S3 so sadly not something we can just drop in, but we could look at building an implementation for Firebase Storage; or see if there is something already out there (eg. there is a [Google tutorial](https://cloud.google.com/solutions/automating-malware-scanning-for-documents-uploaded-to-cloud-storage) that uses Cloud Functions to check uploaded files, which could be neat)

**Comment by crablab** [comment]
HMRC also have an implementation of ClamAV for S3: https://github.com/hmrc/upscan-initiate/blob/master/README.md

**Comment by crablab** [comment]
@warrensearle Here is the turnkey solution I spoke about in the call: https://aws.amazon.com/marketplace/pp/B07XFR781T

I think this might be a really viable option for us, given the low quantity/volume of files we have.

**Comment by crablab** [comment]
Tested out the GCP option which seems to work really nicely. [Slack thread](https://judicial-appointments.slack.com/archives/CLV1P6D6J/p1594804250057800)

Will need to discuss if we want to use this and, if so, how we want to ticket this and gradually roll it through to production.

**Comment by warrensearle** [comment]
Nice work @crablab lets discuss further and make a plan.

**Comment by crablab** [comment]
Thanks @warrensearle :smile: Always best to try something out, before one claims vigorously that it won't work :stuck_out_tongue: :sweat_smile: 

Let me know if you'd like to jump on a call to discuss quickly. 

My immediate thoughts are:
- Do we want to go with this? (I think it will probably be a yes, but best to demo and understand exactly what we're signing up for first)
- Can we add the function to `digital-platform`?
- How will we maintain the Google App Engine container and where should it go in our repos? 
- Do we need any deployment pipeline beyond triggering it in `gcloud`?
- Can we easily change our codebase to write to one bucket and read from another? (Thought: this might not place nice with the SDKs)
- Do we want to wait for the suggested changes to file handling (eg. a separate collection with metadata) before we make this change? (so we can track when stuff is uploaded, scanned and the result)

**Comment by crablab** [comment]
`gcloud tasks queues create {queue id}`

**Comment by HalcyonJAC** [comment]
Spoke to @warrensearle about this ticket...

Development Plan:

- [ ] When files are uploaded they should trigger a cloud function that performs the virus scan.
- [ ] Once a file has been scanned a 'scanned date/time' meta property should be set against the file.
- [ ] If a file is deemed malware (i.e. a virus) it's filename should be appended with `.infected`
- [ ] Storage rules should be updated so that they only allow files to be downloaded that have been scanned and are not infected.

Note: Instead of adding a meta property, we could add an '.unscanned' extension to files when they are uploaded and remove it after a clean scan.

**Comment by HalcyonJAC** [comment]
Technical notes:

- when deploying from the Google Cloud CLI I had to deploy (using the command below) twice to get it to install everything it needed:
 - `gcloud app deploy`

**Comment by HalcyonJAC** [comment]
Proof of concept

- I launched a Virtual Machine on my PC and created an eicar.txt file with the following content:
  - `X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*`
  - Ref: https://en.wikipedia.org/wiki/EICAR_test_file
- I uploaded the file to exercise `miJIQrVCOVV4ZxVXxVlU` as the _Skills and Abilities Criteria_ file. See screenshot here:
  - ![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/8775766c-b066-4c33-b0ee-7aabc30935ad)
- I then checked the metadata of the file in google storage:
  - ![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/b07655a6-33fe-4d01-8555-435ce8386edb)
- For comparison, here is the metadata of another file I uploaded:
  - ![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/56486a15-53ae-48c5-8725-f0b865e437f0)
- and here is what the _Exercise Downloads_ page looks like:
  - ![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/34c1d50f-5238-4fbc-98ab-73a9d390c8ac)
  - Note: You can't download the eicar.txt file

**Comment by HalcyonJAC** [comment]
...just noticed that the hosting costs have jumped up the last couple of days, i.e., since deploying the App Engine on develop...

![image.png](https://images.zenhubusercontent.com/603e1836d75b05b4fc7c9c59/3d924dce-2e41-42a8-8b5d-88dc373ea737)

**Comment by HalcyonJAC** [comment]
A few things to explore with @warrensearle :

- Review the end-to-end working solution (it is demoable).
- See if there is a way to avoid having to start the ClamAV service manually.
- Explore what options we have to reduce the hosting costs of this solution. Note: It is currently estimated to be £2/day per instance (i.e. per platform).

**Comment by KateMJAC** [comment]
Based on conversations and approval by Matt and Sharon at the 2/07/21 Digital Stand-up this work is to be progressed. 

It was asked that we just set up a way to monitor the costs and if they nudge over the estimated £2 a day, we get it flagged and escelated.

**Comment by HalcyonJAC** [comment]
Next steps:

- Scan all existing files
- Allow one instance of the app to scan develop, staging and production.
- Resolve deployment problem so that ClamAV service does not have to be started manually during deployment.

**Comment by HalcyonJAC** [comment]
To setup billing alerts: https://cloud.google.com/billing/docs/how-to/budgets

**Comment by KateMJAC** [comment]
Contact has been made with Josh to assist in setting up alerts, as the devs and I don't have the required level of access.
