### ISSUE TITLE
Update list of commissioners and change functionality to utilise global list of commissioners

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2248]
**Background**
There are 6 new commissioners joining in December and some existing commissioners departing at the end of the year, hence the database needs to be updated and assurance provided that exercises are always using the up to date list of commissioners. As commissioner conflicts will be reconfirmed prior to Selection day set-up, there is no impact caused by changes to the list mid-exercise. Also a snapshot of the commissioner is taken for the exercise, hence even if the commissioner is no longer on the list, they will still be stored in the exercise record as the then commissioner.

**User Story** 
As the Digital team, I would like the commissioner contacts dropdown and the commissioner conflicts (and reconfirmation of) to be constantly up to date so that the current live list of commissioners is displayed to users and candidates.

**Feature(s) Description** 

-  Iterate platform to reference the global list of commissioners rather than the list being added to each exercise
-  Update the global list with the new commissioners
[New Commissioners 14.12.23.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHBmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5005f66a1ee93ebb973eab9cfaad41399e8f82ca/New%20Commissioners%2014.12.23.xlsx)

**Tasks**

- [x] Admin. Use global list of commissioners rather than an exercise-specific copy
- [x] Digital Platform. Remove code which copies commissioners to vacancy
- [x] Digital Platform. New background function to copy commissioners to public list of commissioner names.
- [x] Digital Platform. Security rules to allow candidates to read list of commissioner names
- [x] Apply. New vuex store to read public data from `services/candidateData` document
- [x] Apply. Use global list of commissioner names in commissioner conflicts feature
- [x] Firestore. Update commissioners data in develop, staging and production environments
