### ISSUE TITLE
Merit list moderation - Draft

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2296]
**Background**
Following the most recent workshop in January, we have gathered the user requirements for moderation on the platform and these are detailed below. Broadly, we want to support moderation; keeping track when scores change, identifying when we want to allow changes to be made.

**Feature**
**_3 buttons for SET usage; A button for calibration, a button for moderation, a button with an unlock mechanism with approvals, to enable the SETs to make changes at any time._**

**User Story** 
As an admin, I would like the platform to identify all candidates with one 'D' in a competency, in the post moderation stage so that the candidate can progress to selection day.

As an admin, I want a button for moderation with an unlock mechanism with approvals, so that I can make changes if the grades change after the moderation window has closed. _-(The merit list already shows the candidates who are flagged (identified for moderation) by the panel chairs. The teams can select additional candidates for moderation by taking a sample of the As, Bs, Cs and Ds + the highest number from around the cut-off line. The teams state which panel will be the moderating panel for each of those candidates. The selection exercise teams will confirm, the button reopens the panel portal and the reports to be moderated by each of those panels. Only the moderation reports with the grades of those candidates they’re moderating, are displayed to those panel members who go to the reports in Google Drive.)_

As an admin, I want to see a confirmation button asking 'Are you sure you want this grade changed?' so that I can input the updated grades and input the reasons reasons why the grade change occurred. 

As a panellist, I want to be able to input the grades directly onto the merit list via the panellist's app so that grades can be seen in real-time. 

As a panellist, I want to see the candidates grades on the platform and be able to input commentary against each of those candidates. I want to be able to suggest changes to the grading if needed and submit. 

As an admin, I want that information funnelled back into the merit list and track the suggested changes to final appraisal so that I can confirm I'm satisfied with the changes and save a new version of the merit list with the updated grades.

**Ticket Champion**
Matt

**Acceptance Criteria**
 - [ ] Given the moderation stage has started, when the platform identifies candidates with one 'D' in a competency, then those candidates should be flagged for further review

- [ ] Given the platform is in the post moderation stage and the grades may change after the moderation window has closed, when an admin clicks on the moderation button and the admin provides necessary approvals, then the panel portal should reopen and the reports to be moderated should be displayed

- [ ] Given an admin updates a grade, when the admin inputs the updated grade and confirms the grade change, then the platform should display a confirmation message and the admin should be able to input the reasons for the grade change

- [ ] Given a panellist is using the panellist's app, when the panellist accesses the merit list and inputs grades for candidates,  then the grades should be visible in real-time on the platform

- [ ] Given a panellist can view the candidates' grades on the platform, when the panellist inputs commentary for each candidate and submits the changes, then the platform should track the suggested changes to final appraisal

- [ ] Given an admin is reviewing the suggested changes to the merit list, when the admin confirms the changes and saves a new version of the merit list with the updated grades, then the updated merit list should be saved and accessible on the platform

**Comment by NormaJAC** [comment]
DUPLICATE ticket, close it.
