### ISSUE TITLE
Merit list functionality on the platform

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2302]
**Background**
Currently, Merit list activities are largely conducted off-platform by SETs. A merit list meeting was held on 09/10/2023 to better understand requirements, this was followed up with workshops on 29/11/23 and 19/01/24, the latter to better understand moderation and calibration activities and merit lists for multi-jurisdictional exercises.

The next steps are:

- Prepare panellist app for testing
- Test panellist app internally
- Test panellist app with SETs (on a live exercise?)
- Build in moderation functionality on the platform
- Develop functionality for merit lists on multi-jurisdictional exercises

## Acceptance Criteria

- [ ] **Scenario 1: Prepare panellist app for testing**
  - The panellist app is prepared for testing
  - The app includes all required features and functionalities
  - The app is compatible with different devices and operating systems

- [ ] **Scenario 2: Test panellist app internally**
  - The panellist app is tested internally by the development team
  - All features and functionalities of the app are tested
  - Any bugs or issues found during testing are fixed

- [ ] **Scenario 3: Test panellist app with SETs**
  - The panellist app is tested with SETs (Subject Matter Experts)
  - SETs are able to use the app effectively and efficiently
  - Any feedback or suggestions from SETs are collected and addressed

- [ ] **Scenario 4: Build in moderation functionality on the platform**
  - Moderation functionality is added to the platform
  - Moderators are able to review and moderate merit lists
  - Moderation activities are logged and auditable

- [ ] **Scenario 5: Develop functionality for merit lists on multi-jurisdictional exercises**
  - Functionality for merit lists on multi-jurisdictional exercises is developed
  - Merit lists can be created and managed for exercises involving multiple jurisdictions
  - The platform supports the unique requirements of multi-jurisdictional exercises
