### ISSUE TITLE
Moderation on the platform Scenario test - Panellist's app/portal DRAFT

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2367]
## Background
Currently, Merit list activities are largely conducted off-platform by SETs. A merit list meeting was held on 09/10/2023 to better understand requirements, this was followed up with workshops on 29/11/23 and 19/01/24, the latter to better understand moderation and calibration activities and merit lists for multi-jurisdictional exercises.

The next steps are:
Prepare panellist app for testing
Test panellist app internally
Test panellist app with SETs (on a live exercise?)
Build in moderation functionality on the platform
Develop functionality for merit lists on multi-jurisdictional exercises

## User Story

- [ ] PANEL PORTAL
As a moderating panel chair, I would like to search the moderation exercise list so that I can view all exercises for moderation with ranked candidates, including flagged candidates.
As a moderating panel chair, I would like to click on a sift for an exercise so that I can view a candidate's original grades.
As a moderating panel chair, I would like to click on the moderation button so that I can view the moderation drop down box.

- [ ] MODERATION DROP-DOWN BOX
As a moderating panel chair, I would like to click on the 'Panels' arrow so that I can enter the moderated grade and the reason for moderation in the appropriate box for each question.

## Feature(s) Description
Clearly describe the new functionality/change(s) to existing functionality.
Include a link to a Miro board/image if appropriate.

- [ ] Feature

## Acceptance Criteria 

 - [ ] **Moderation on the platform**
  - When a moderating panel chair is logged in and they search for the moderation exercise list, then they can view all exercises for moderation with ranked candidates, including flagged candidates
- [ ] **Viewing a candidate's original grades**
  - When a moderating panel chair is logged in, and they click on a sift for an exercise, then they can view a candidate's original grades
- [ ] **Moderation button functionality**
  - When a moderating panel chair is logged in, and they click on the moderation button, then they can view the moderation drop-down box
- [ ] **Entering moderated grade and reason for moderation**
  - When a moderating panel chair is logged in, and they click on the 'Panels' arrow, then they can enter the moderated grade and the reason for moderation in the appropriate box for each question

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
