### ISSUE TITLE
Moderation on the platform Selection Day - Panellist's app/portal DRAFT

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/admin#2369]
## Background
Currently, Merit list activities are largely conducted off-platform by SETs. A merit list meeting was held on 09/10/2023 to better understand requirements, this was followed up with workshops on 29/11/23 and 19/01/24, the latter to better understand moderation and calibration activities and merit lists for multi-jurisdictional exercises.

The next steps are:
Prepare panellist app for testing
Test panellist app internally
Test panellist app with SETs (on a live exercise?)
Build in moderation functionality on the platform
Develop functionality for merit lists on multi-jurisdictional exercises

## User Story

- [ ] PANEL PORTAL
As a moderating panel chair, I would like to click on a sift for an exercise so that I can view a candidate's overall and combined grades and bands.
As a moderating panel chair, I would like to click on the moderation button so that I can view the moderation drop down box.

- [ ] MODERATION DROP-DOWN BOX
As a moderating panel chair, I would like to click on the grades arrow so that I can enter the moderated grade and the reason for moderation in the appropriate boxes for Overall, Combined, Roleplay and Interview (EJ, PBK, ACI, WCO, MWE).
As a moderating panel chair, I would like to click on the submit button to submit the moderated grades for each candidate.
As a moderating panel chair, I would like to click on the moderation button so that I can view the' moderation report' drop down box.
As a moderating panel chair, I would like to click on the grades arrow so that I can enter the final moderated grade and the reason for moderation in the appropriate boxes for EJ, PBK, ACI, WCO, MWE.
As a moderating panel chair, I would like to click on the submit button to submit the final overall band/grades grades for each candidate.
As a moderating panel chair, I would like to click on the 'Confirm moderation' button in the moderation drop-down box so that I can input the final grades/bands and state the reasons in the note box.

## Feature(s) Description
Clearly describe the new functionality/change(s) to existing functionality.
Include a link to a Miro board/image if appropriate.

- [ ] Feature

## Acceptance Criteria 

It's done when...
 - [ ] **Panel chair views candidate's overall and combined grades**
  - Given the panel chair is moderating a candidate, when the panel chair clicks on the sift for the exercise, then the panel chair can view the candidate's overall and combined grades
- [ ] **Panel chair enters moderated grades and reasons**
  - Given the panel chair is moderating a candidate, when the panel chair clicks on the moderation button, then the panel chair can enter the moderated grade and reason for moderation in the appropriate boxes for Overall, Combined, Roleplay, and Interview
- [ ] **Panel chair submits moderated grades**
  - Given the panel chair is moderating a candidate, when the panel chair clicks on the submit button, then the moderated grades are submitted for the candidate
- [ ] **Panel chair views moderation report**
  - Given the panel chair is moderating a candidate, when the panel chair clicks on the moderation button, then the panel chair can view the moderation report drop-down box
- [ ] **Panel chair enters final moderated grades and reasons**
  - Given the panel chair is moderating a candidate, when the panel chair clicks on the 'Confirm moderation' button in the moderation drop-down box, then the panel chair can enter the final moderated grade and reason for moderation in the appropriate boxes for EJ, PBK, ACI, WCO, MWE
- [ ] **Panel chair submits final overall band/grades**
  - Given the panel chair is moderating a candidate, when the panel chair clicks on the submit button, then the final overall band/grades are submitted for the candidate

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)
