### ISSUE TITLE
Exercise stages and application status

### ISSUE THREAD

**Issue by londonprojects** [jac-uk/admin#247]
We use a status to distinguish candidates throughout the process.  It helps us move candidates through the different stages in the exercise process.  Using statuses has helped us report more easily on progression through the exercise and overall exercise trends year on year. It is also a requirement to move candidates through statuses and stages to accurately capture diversity data. 

This epic consists of:
1) Stages
2) Statuses 

In each stage Admin needs the ability to update the statuses of candidates which will then push them through the stages in an exercise: 
1) Individually
2) In bulk

Eventually we want admins to use these updates to trigger notify emails to the relevant candidates. Please note the way these stages and statuses are created must leave room for future automation and email triggers but these won't be looked at until phase 2. 

This is the list of stages and statuses: https://docs.google.com/spreadsheets/d/1S6qpdM5DchujfNT0v0wUfpnVijtwor8sTcu44oB8E9A/edit?usp=sharing

This consists of the following tickets: 

- [x] create heading 'Applications' on left menu with 'Applied', 'Draft' and 'Withdrawn' underneath ticket #441

- [x] creating the stages ticket #436

- [x] create candidate statuses for Review stage ticket #437

- [x] create candidate statuses for Shortlisting stage ticket #438

- [x] create candidate statuses for Selected stage ticket #439

- [x] create candidate statuses for Recommended stage ticket #440

- [x] create set status button ticket #442

- [x] banner heading when a status is updated ticket #452

- [x] create tick boxes (individual, bulk, select all) for status update ticket #443

- [x] creating a move back option ticket #453

- [ ] EMP flag creation ticket #455

- [x] connecting statuses and stages so the candidates appear in the correct list ticket #451

- [ ] an issues column appearing and the candidate not moving to handover if an issue is outstanding ticket #254

- [ ] exercise moves into closedown automatically when handover completed and then closed after 18 months ticket #456
