### ISSUE TITLE
Introduce Processing Version 3.0

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#2475]
In 'Processing version 2.0' we introduced a new set of stages and statuses.

Here we are introducing 'Processing version 3.0' which will include new Tasks (PSDQ, Sift, Selection Day etc).

_Note the new tasks were previously included in version 2 and causing confusion for SETs so this change will resolve that._

**To Do**

- [x] Add Processing version 3.0 to the configuration area in Admin (see screen grab below)
- [x] Update code to ensure new tasks only show for version 3+
- [x] Ensure Exercise > Additional Settings only shows for version 3+
- [x] Ensure the stage & status migration code only runs when changing between version 1 and 2 (not for changes to version 3+)

**Config page**
<img width="1198" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3VuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a37906b9f8bda33ffa2b2c4badbdd2ed3facb2a6/image.png" alt="image.png" />

**Tasks for 2.0**
<img width="1289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b365d67800ece0e52b2f539e135a1ee9caa9c8d5/image.png" alt="image.png" />

**Tasks for 3.0**
<img width="1212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02f38cc5c3305ad9bb6c68f78a1acec242146381/image.png" alt="image.png" />
