### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#315]
As a product owner I want all admin users have the right levels of access so that I can ensure that the system restricts potentially dangerous action like deletions being available to all

I want seven different types of user and the ability to assign and amend roles.  The Super Admin roles are within the digital team, the Manager and Admin are JAC staff but at different seniority. Panel member are the people who interview the candidates and Commissioners do interview but also make the final decision when they sit as the Selection and Character Commission. The external roles are candidate which is self-explanatory and assessor, an assessor is basically a referee but we call them independent assessors. The roles further explained are:

1. **Admin side**

- **Super Admin:** Digital team admins with the ability to delete and adjust live exercises.  They also have all the permissions the other roles have

- **Manager:** they have sign off ability and the functions that an admin would have and are able to search and review all exercises. 

- **Admin:** they have specified functions including the ability to amend applications within their specific exercises

- **Panel member:** ability to see modified candidate information for their panel candidates only

- **Commissioner:** ability to see modified candidate information (this will vary particularly around diversity) 

2. **Candidate Side**

- **Candidate:** the ability to create an account, create, save and review applications.  Ability to withdraw their own applications

- **Assessor:** the ability to receive a link to complete either a download or upload of an assessment. Eventually the ability to register for an account and review and reuse previous assessments.  

Related information.
This spreadsheet outlines the seven role permissions.  See separate tabs for each role.  
https://docs.google.com/spreadsheets/d/1hkI1vlIC89AII4MgiK9qYtAXRoa27bCOM9Ric1oWdSQ/edit#gid=1483517511

This ticket consists of: 

- [ ] Creating a Super Admin role with related permissions ticket #377

- [ ] Creating an Admin role with related permissions ticket #378

- [ ] Creating a Manager role with related permissions ticket #379

- [ ] Creating a Panel Member role with related permissions ticket #380

- [ ] Creating a Commissioner role with related permissions ticket #381

- [ ] Creating a candidate role with related permissions ticket #382

- [ ] Creating an Assessor role with related permissions ticket #383

- [ ] Going in and updating the existing users to reflect their roles. At the moment everyone on Apply is a candidate but we need to reflect this before IAs start being collated on the platform. Claire and Becky could go through the roles as Super Admin on the staff side and assign them the right credentials ticket #385

**Comment by mbrookeswebdev** [comment]
[There is a branch in Admin repo with some prototype code written for ticket 1147](https://github.com/jac-uk/admin/tree/feature/1147-approach-to-implementing-user-roles).

**Comment by londonprojects** [comment]
I am closing this epic due to new requirements
