### ISSUE TITLE
QTs MVP

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#404]
**Original requirements:**
- Link QT to candidate application by way of a single sign on via their platform account
- Link QT results to the candidate on their application on the admin view 
- Provide either a visible timer or time stamp or the ability to auto submit any answers at the end of the allocated time
- Vary time limits when candidates are given extra time to complete their tests.  

We've decided to move Scenario QTs onto the platform as an MVP for wider migration onto the platform. This needs to be done by the beginning of September so we can test in time for the Recorder exercise later that month. 

Please see below for rationale and decision making

**Comment by crablab** [comment]
Current QTs:
- Situational Judgment (1 part)
- Critical Analysis and Situational Judgment (2 part)
- Scenario 

The tests have the following input methods:
- Situational Judgement: statement with 4 possible options, choice between "Most appropriate" and "Least appropriate" 
![screenshot_2020-07-29-131041.png](https://images.zenhubusercontent.com/5ee73e89ae6caf2243b458bb/d95c7c83-3c21-41ee-ba8e-df12b3781485)
- Critical Analysis: question/statement with 4 radio button choises
![screenshot_2020-07-29-131206.png](https://images.zenhubusercontent.com/5ee73e89ae6caf2243b458bb/797ad221-91a8-44d1-854c-710a591efca7) 
- Scenario: textual statement plus a number of long form text responses. 
![screenshot_2020-07-29-131345.png](https://images.zenhubusercontent.com/5ee73e89ae6caf2243b458bb/7a570738-4d0d-46de-979e-bf4b23baa32a)

**Comment by crablab** [comment]
As discussed with Becky, some of the issues are:
- No timer 
- No word count on long form responses
- Formatting is removed when copying from Word to the Google Form 

There are a few potential solutions. 

## Embedded Google Form
- Allows us to solve the timer issue fairly quickly and can be implemented for all QTs, at once. 
- Might look/behave a bit jankily when iframed within the platform 
- Relies on correct use/sharing of the Google Forms (which is an issue at the moment) 
- Doesn't solve word count or formatting issues 
- Results are still off platform 

## Document upload for scenario QTs
(Nb. as an aside from whatever happens with the other QTs)
- Allows unlimited formatting in Word (do we really want that?)
- Timer can be displayed on platform, but not visible when candidates are working in Word
- Requires downloading each file to mark, as opposed to viewing responses directly in the platform (as with a text field)

## Form generation, displaying and submission for QTs on platform 
- Most complete solution 
- Timer and word count possible 
- Resolves issues with Google Form creation and sharing
- More restrictive options available when creating a QT
- Doesn't necessarily fix formatting issues
- Complex

**Comment by crablab** [comment]
https://moj-design-system.herokuapp.com/components/rich-text-editor

**Comment by crablab** [comment]
Summary of discussion today:
- Not possible to embed a countdown timer within Google Forms
- Could embed Google Forms in platform with countdown timer in platform 
- Likely to cause a number of UI, UX, browser compatibility issues, plus operational headaches
- This is a fallback option. 
- Discussed that scenario QT for Recorder in September is likely the next  QT that needs to run, and therefore aim is to provide an MVP for a scenario test 
- Most of the work likely to be in the set up for handling QTs on the platform (new pages, making the countdown, handling start/finish etc.) so Google Form embed not necessarily a big time saving anyway! 
- Plan to handle the simplest test scenario first and then expand to other tests later. Possible to include a Google Forms embed for other tests if required. 
- Load unlikely to be a problem. As with Google Forms, the platform is scaled by Google and 3500 candidates is really nothing for Firebase. Potential for application bugs - perhaps run a JAC wide QT to do a shakedown and inform go/no go?

**Comment by crablab** [comment]
Note: we're only supporting scenario tests right now. 

Tickets we need for this: 
- [ ] Admin: create new Countdown timer component (possible based on Monika's?) 
- [ ] Admin: create new Qualifying Test page under Tasks 
- [ ] Admin: if QT not initialised, create SJQT workflow 
- [ ] Admin: for initialised scenario test, review and edit the QT 
- [ ] Admin: review candidates queued for the initialised QT 
- [ ] Admin: highlight those with requested reasonable adjustments and apply reasonable adjustment to their timings
- [ ] Admin: kick off QT (email to candidates)
- [ ] Admin: see candidates that have started the QT and at what time 
- [ ] Admin: see aggregate numbers of sent QTs, attempted QTs and completed QTs 
- [ ] Admin: review completed QTs and apply marks 
- [ ] Admin: (TBC) display marks/sort by marks in Shortlisted to allow candidates to be filtered 

- [ ] Apply: new page to show outstanding and completed QTs 
- [ ] Apply: 'start' page for QT 
- [ ] Apply: Scenario QT entry page (with countdown timer)
- [ ] Apply: Scenario QT completion page (with summary)
