### ISSUE TITLE
Automated Panel Packs 

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#410]
Find a way to select fields to be generated in panel pack and automatically combined with candidate assessments and independent assessments received.  

May require further development for panels beforehand so may need to shift

**MVP**

- [ ] Integration with google drive including docs and sheets with platform 

- [ ] area in admin where you add the drive for the exercise. Suggest you can use a search in a drop down menu to find the drive if already created BUT also create it if you have not done so. Suggest this goes in vacancy information 

- [ ] Create a task area called 'Panels'. In this area teams will add panel names and the individual members within that panel. Suggest an 'add panel' button and then a modal appears for 'Name of panel', 'Interview dates', and a section called 'Members' where they can type a name for the Chair: ________, Independent:________, Judicial:_______,Other:_________. There should be an option to add another 'Other' just in case we have panels of more than 4. As the panels are created a folder is created in the google drive. For example the following folders Panel 1, Panel 2, Panel 3 and within those panels there is a folder for each Panel member. So if you had say Panel 7 with Tom Russell, Warren Searle and Jeremy Suarez a folder is created in the exercise drive 'Panel 7' and then within that folder there are subfolders called 'Tom Russell' 'Warren Searle' 'Jeremy Suarez'. 

Eventually this area will connect to the panellists app so would suggest they can auto search for users who have been added to that app into the future. 

- [ ] Add 'Assign to panel' button in each of the stages. The team click the check box and add the candidates they want to each panel. Those names then appear under the panel in the tasks. 

- [ ] From the 'Panels' area there will be a button to 'Export panel packs'. When they click this they appear in google. 

- [ ] The specific packs for each panel appear in each of the panel members folders on google drive. So in our above example folders for each candidate appear in the Tom Russell, Warren Searle and Jeremy Suarez folders. If the download happened at 'Review' stage the folder is named after the Application reference. For simplicity this should only be the digits after the -. Ie. JAC00351-fiz0003 would be fiz0003. **BUT** if they are in 'Selected' and the status is 'invited to selection day' the folder needs to be their Name as this is not name blind. 

- [ ] The panel pack needs to be updated so they are all in Arial, font size 11 and all the headings are in bold. The independent assessor details **must** be removed. These are not required in the pack as they get the actual assessments to read. 

- [ ] Within the folder for each candidate the following documents need to appear:

1. the panel pack: https://admin-staging.judicialappointments.digital/exercises/5YbFGOQ8TagXkO4RZfEO/application/VcvlNysWH0GsGtnOtHx6#panel
2. the independent assessments that were sent in (these will be in independent assessments - tasks). There are normally but may only be 1. 
3. Anything the candidate had to upload such as a candidate assessment. These appear at the bottom of the panel pack as attachments but need to be added to the folder as well. This could be more than one document and they will need to appear separately. 
4. A list to keep track of their scores. You will need to ask Kate Malone to find an example

- [ ] Suggest the following names: 'Application' for 1, 'Independent Assessment 1' and/or  'Independent Assessment 2' for 2. and for 3 whatever the file is called e.g. 'candidate assessment'. 

- [ ] The team will keep a record of scores in a sheet. We need to add an 'Import to digital platform' button to this sheet for when it is ready. It will then populated scores under 'Reports' in a report called 'Merit list'. There will be future work here but for now it will just be a mechanism to keep a record of the scores put into google drive. It will also inform which emails certain candidates get.

**Comment by Rebecca-mcknight1991** [comment]
@joy-ade you need to ticket this up first thing when back.

**Comment by Rebecca-mcknight1991** [comment]
@KateMJAC top priority when back.

**Comment by KateMJAC** [comment]
Joy and Kate to seek advice from SEOs re file structures and benefit of combining files.

**Comment by warrensearle** [comment]
@KateMJAC @joy-ade @lloback @warrensearle in our meeting today we discussed breaking this epic down into the following parts:

- Create Panel & Add Panelists (user stories; scenarios, visual)
  - Specify google drive to use
- Assign Candidates to Panel
- Generate Files & Copy to Folder Structure (the magic! approx 20 SPs)

We also have the following questions / spikes:
- Can team provide us sufficient permissions to access Google Drives
- Can we add permissions to Drive folders?
