### ISSUE TITLE
Testing QTs

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#817]
We need to ensure the Qualifying Tests feature is well tested and we have high confidence in the robustness of our solution. Some initial questions:

- How well does our solution handle 1000s of applicants?
  - Initialising the test
  - Sending invitations
  - Opening (activating) the test
  - How long between the first and last 'test is open' updates
  - How long between the first and last 'test is open' emails
  - Monitoring progress when the test is live. Is it laggy?
  - Calculating scores
  - Exporting data
  - Importing modified data (e.g. scenario scores)
- How confident are we in timing tests and that the system cannot be cheated or allows for network latency?
  - What is our tolerance for data being submitted in the UI and being accepted as 'in time' - 1 second, 1 minute?
  - What happens if a user changes the local time on their computer / device?
- How well does the journey work across browsers and devices?
- How accessible is the test?

Most of the questions around load performance are mitigated by the simple fact that we're using google platform: 1000s of concurrent users really is small fry! That said there would be value in testing and measuring the performance of specific parts of our solution. Likewise given the high level of confidence demanded there is value in being able to simulate (and demo) 1000s of concurrent users so we should look at options for this.

The following tasks would be useful:

- [ ] Generate dummy applications for an exercise. See digital platform ticket digital-platform#388
- [ ] Measure performance of back end routines. See digital platform digital-platform#389
- [ ] SPIKE: what tools could help with simulating concurrent users. See ticket apply#393
- [ ] End to end (e.g. cypress) tests for starting and submitting a test, running out of time etc. See ticket apply#394
- [ ] Measure performance of dashboard & lists when dealing with 1000s of live candidates. See ticket #822
- [ ] Capture a screen recording of the live dashboard showing tests starting, completing etc. See ticket #823
- [ ] Browser testing. See ticket #395
- [ ] Accessibility check. See ticket #396
- [ ] Write manual test scripts & instructions. See documentation#17
- [ ] Manual testing
