### ISSUE TITLE
Invitation-only Exercises

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#915]
**User stories**

As an Admin
I would like to create an 'Invitation only' exercise
So that I can invite a specific set of candidates to apply for the exercise
and no-one else can apply to the vacancy

As a candidate
I would like to know if I have been invited to apply for an exercise
So that I can find out more and start my application

---

**Admin tasks** 
See admin#934
- [x] Website listing. Include a checkbox to specify 'Invitation only exercise'. 
- [x] New page: Invitations. Should show only for invitation-only exercises. List of all current invitations plus a mechanism to add (and remove) email addresses. (this is similar to Dry Run QT).

---

**Platform tasks** 
See digital-platform#421
- [x] Include the 'Invitation only exercise' flag in the exported vacancy documents
- [x] Ensure candidates can access their own Invitations and mark them as accepted/rejected

---

**Apply tasks** 
See apply#507 and apply#525
- [x] Invite-only exercises will not display in any of the vacancies lists
- [ ] @Rebecca-mcknight1991 Should we prevent anyone without an invite from seeing the details page?
- [x] A banner will display to any logged in user invited to apply containing the text: "You are invited to apply for #LINK_TO_VACANCY_DETAILS#" (see visual below). This will only show whilst the vacancy is accepting applications and before the candidate has started an application
- [x] For invited users the vacancy details page will display a button to "Start application"
- [ ] Invitation should disappear after user has accepted it. See apply#525
- [ ] Only allow an application to be started if the user has a valid invitation. See apply#525

![Screenshot 2020-10-05 at 15.33.55.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/ca69f1cf-6350-4ef5-bb15-28e9401667d0)

---

**Proposed data model for `Invitations` documents**
```
{
  vacancy: {
    id: String,
  },
  candidate: {
    email: String,
    id: String,  <-- populated when candidate accepts/rejects the invitation
  },
  status: 'created' | 'invited' | 'accepted' | 'rejected', 
  statusLog: {
    created: Timestamp,
    invited: Timestamp,
    accepted: Timestamp,  <-- populated when candidate accepts the invitation
    rejected: Timestamp,  <-- populated when candidate rejects the invitation
  }
}
```

**Comment by lloback** [comment]
![image](https://user-images.githubusercontent.com/15261814/95322642-b7fe2400-0894-11eb-8b49-a89fb93ab5a1.png)
