### ISSUE TITLE
Ability to filter, select exercises and Download data

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#959]
Update the exercises list to include:
- [ ] filters by date range based on exercise open date, close date or SCC date. See admin#993
- [ ] filter by stage. e.g. Review, Shortlisting, Handover/Completed. NOTE: This relies on admin#1002
- [x] Button to download data. This will call a cloud function to return the data. See digital-platform#456
